### ISSUE TITLE
cual version de nodejs es necesaria ?

### ISSUE THREAD

**Issue by AlonsoK28** [meta-dapp/trading-bot#3]
actualmente estoy usando la version `node.js 16` y me indica el siguiente mensaje de error en la consola

```cmd
/trading-bot/binance/node_modules/binance-api-node/dist/http-client.js:102
        error = new Error(json.msg || "".concat(res.status, " ").concat(res.statusText));
                ^

Error: Illegal characters found in parameter 'symbol'; legal range is '^[A-Z0-9-_.]{1,20}$'.
    at /trading-bot/binance/node_modules/binance-api-node/dist/http-client.js:102:17
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getMinBuy (/trading-bot/binance/app.js:468:25)
    at async init (/trading-bot/binance/app.js:495:20) {
  code: -1100,
  url: 'https://api.binance.com/api/v3/exchangeInfo?symbol=NaN'
}
```

actualmente cual es la version oficial de `node.js` de este proyecto?

saludos

**Comment by csalazart** [comment]
Hola 
1. Si Estoy deacuerdo en que falta documentación
2. No es la version de node esa esta bien puede ser 16 o 20 si prefieres.
3.  si te fijas en el error at async init (/trading-bot/binance/app.js:495:20) { 
  el problema va en la linea donde esta 
  `const minBuy = await getMinBuy()`
luego si te vas a la funcion getMinBuy descubre que:  
 `const { symbols } = await client.exchangeInfo({ symbol: MARKET }) ` ooh sorpresa lo dice el error
` at async getMinBuy (/trading-bot/binance/app.js:468:25)`
 y resulta que  `{ symbol: MARKET }`  => MARKET es una constante declarada arriba en la linea 11
`const MARKET = MARKET1 + MARKET2 ` 
que a su vez depende de 2 variables mas
```
 const MARKET1 = process.argv[2]
const MARKET2 = process.argv[3] 

```
que sucede que necesitas pasarle unso parametros a la invocación de la funcion que determina el los symbolos y del mercado que vas a operar..
lo cierto es que tienes que investigar y leer el codigo para entender que sucede.. 
Este chico lo explica un poco en algunso de sus videos en youtube 
Este conjunto de bot tiene algunso mas fallos ya que lo he testeado y probado solo funciona en mercados alcistas y aveces no ahce las operaciones correctamente. y se puede mejorar muchisimo mas la verdad cosa que tambien realize mas cambios 
asi que si quieres ponerlo a trabajar tendras que asegurarte que funcione bien.. 

Este tipo de scripts bot aca es recreativo y a modo educativo para aprender tal como lo mencionan en los videos del chaval.

**Comment by AlonsoK28** [comment]
> Hola
> 
> 1. Si Estoy deacuerdo en que falta documentación
> 2. No es la version de node esa esta bien puede ser 16 o 20 si prefieres.
> 3. si te fijas en el error at async init (/trading-bot/binance/app.js:495:20) {
>    el problema va en la linea donde esta
>    `const minBuy = await getMinBuy()`
>    luego si te vas a la funcion getMinBuy descubre que:
>    `const { symbols } = await client.exchangeInfo({ symbol: MARKET }) ` ooh sorpresa lo dice el error
>    ` at async getMinBuy (/trading-bot/binance/app.js:468:25)`
>    y resulta que  `{ symbol: MARKET }`  => MARKET es una constante declarada arriba en la linea 11
>    `const MARKET = MARKET1 + MARKET2 `
>    que a su vez depende de 2 variables mas
> 
> ```
>  const MARKET1 = process.argv[2]
> const MARKET2 = process.argv[3] 
> ```
> 
> que sucede que necesitas pasarle unso parametros a la invocación de la funcion que determina el los symbolos y del mercado que vas a operar.. lo cierto es que tienes que investigar y leer el codigo para entender que sucede.. Este chico lo explica un poco en algunso de sus videos en youtube Este conjunto de bot tiene algunso mas fallos ya que lo he testeado y probado solo funciona en mercados alcistas y aveces no ahce las operaciones correctamente. y se puede mejorar muchisimo mas la verdad cosa que tambien realize mas cambios asi que si quieres ponerlo a trabajar tendras que asegurarte que funcione bien..
> 
> Este tipo de scripts bot aca es recreativo y a modo educativo para aprender tal como lo mencionan en los videos del chaval.

muchas gracias por su respuesta.

me gustaria ayudar con esas mejoras, validar varios detalles que veo que pueden mejorar y agregar documentacion al proyecto, quizas asi pueda ayudar y aprender mas en este tema del trading.

crees que pueda enviar PR y sea aprovado?

saludos
